### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Aiden-Peace300** [Aiden-Peace300/FilmCritic#1]
## 💰 Motivation

Users will be able to sign up / login to the FilmCritic application and sign out!

## 🖼️ Wireframes

USERS CAN SIGN-UP DESKTOP:
<img width="695" alt="image" src="https://github.com/Aiden-Peace300/FilmCritic/assets/47370726/2bd3c710-583f-4b3f-a7b9-85ac2e71d029">

USERS CAN LOGIN DESKTOP:
<img width="694" alt="image" src="https://github.com/Aiden-Peace300/FilmCritic/assets/47370726/5dc9959b-cf85-4f86-b0f8-48728d9267a2">

USERS CAN SIGN-UP MOBILE:  
<img width="253" alt="image" src="https://github.com/Aiden-Peace300/FilmCritic/assets/47370726/d95c5ede-86bc-4aec-9a88-5103a63ec5d6">

USERS CAN LOGIN MOBILE:  
<img width="252" alt="image" src="https://github.com/Aiden-Peace300/FilmCritic/assets/47370726/5a39cf9e-0311-4bb5-a816-00c2931ffc66">

## ☁️ Server
- [x] Create a file named `verify-token.tsx`. This file will be responsible for verifying the user's JSON Web Token.
- [x] Create a file named `server.tsx` This file is responsible for HTTP methods.
  - [x] Ensure to import `argon2`, `express`, `jsonwebtoken`, along with other files/modules.
  - [x] Implement the POST HTTP method with the path `/api/auth/sign-up` and use PostgreSQL to insert the `username` and `hashedPassword` into the `Users` table
       - [x] This will implement argon2, which will convert the user's password to a hash.
       - [x] Ensure that the username the user chooses cannot be a username that is already in our DB. 
  - [x] Implement the POST HTTP method with the path `/api/auth/sign-in` and use PostgreSQL to search through the `Users` table to check and see if the user entered a `username` and `hashedPassword` that exist.
  - [x] Implement the DELETE HTTP method with the path `/api/users/:userId` and use PostgreSQL to search through the `Users` table to check and see if the userId and username exist and then delete them from the DB.

## ✅ Task List
- [x] Create a React template with the command `npm create vite@latest my-app --template react-ts`
- [x] Create a React component called `NavBar.tsx` that will return JSX for the initial NavBar the user will see (login/register).
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop usage.
- [x] Modify `App.tsx` to call `NavBar.tsx`. 
  - [x] Implement routing from `react-router-dom` to create a user-friendly experience.
- [x] Create a react component called `InsideWebsiteNavBar.tsx` that will return JSX for the NavBar the user will see once they log in to the App.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop usage.
- [x] Test the app by signing up some new users and login with the users, then reloading the page to confirm that:
  - [x] The user isn't signed out.
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
